//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGENT
    {
        public string ID { get; set; }
        public string YWZL { get; set; }
        public string PID { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string YWLX { get; set; }
        public string BRNAME { get; set; }
        public string BRZJLX { get; set; }
        public string BRZJHM { get; set; }
        public string DLRNAME { get; set; }
        public string DLRZJLX { get; set; }
        public string DLRZJHM { get; set; }
        public string ADDLX { get; set; }
        public string ADDRY { get; set; }
        public string ADDDAY { get; set; }
        public Nullable<System.DateTime> ADDTIME { get; set; }
        public Nullable<decimal> ADDTIMESECONDS { get; set; }
        public string ZT { get; set; }
        public string MEMO { get; set; }
    }
}
