//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BMDB
    {
        public string ID { get; set; }
        public string PID { get; set; }
        public string PNAME { get; set; }
        public string BMNO { get; set; }
        public string NAME { get; set; }
        public string BAJGNO { get; set; }
        public string BAJGNAME { get; set; }
        public string BMJB { get; set; }
        public string LXR { get; set; }
        public string LXDH { get; set; }
        public string FZJG { get; set; }
        public string LXDZ { get; set; }
        public string ISJG { get; set; }
        public string MEMO { get; set; }
    }
}
