//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESS_FLOW
    {
        public string ID { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string BID { get; set; }
        public string PTLB { get; set; }
        public string XTLB { get; set; }
        public string YWLX { get; set; }
        public string YWYY { get; set; }
        public string SHMS { get; set; }
        public string BLMS { get; set; }
        public string HPZLNO { get; set; }
        public string HPZL { get; set; }
        public string HPHM { get; set; }
        public string HPHM1 { get; set; }
        public string CLSBDH { get; set; }
        public string CYLSH { get; set; }
        public string BRZJLX { get; set; }
        public string BRZJHM { get; set; }
        public string BRNAME { get; set; }
        public string BRTEL { get; set; }
        public string DLRZJLX { get; set; }
        public string DLRZJHM { get; set; }
        public string DLRNAME { get; set; }
        public string DLRTEL { get; set; }
        public string DWDM { get; set; }
        public string BLDWMC { get; set; }
        public string BRZLS { get; set; }
        public string DLRZLS { get; set; }
        public string DWZLS { get; set; }
        public string ISHMD { get; set; }
        public string DRVANDVEHINFO { get; set; }
        public string OPERID { get; set; }
        public string OPER { get; set; }
        public string OPERTIME { get; set; }
        public Nullable<System.DateTime> OPERTIME1 { get; set; }
        public Nullable<decimal> OPERTIME2 { get; set; }
        public string SPER { get; set; }
        public string SPTIME { get; set; }
        public Nullable<System.DateTime> SPTIME1 { get; set; }
        public Nullable<decimal> SPTIME2 { get; set; }
        public string SPCONTENT { get; set; }
        public string OPER1 { get; set; }
        public string OPER1TIME { get; set; }
        public Nullable<System.DateTime> OPER1TIME1 { get; set; }
        public Nullable<decimal> OPER1TIME2 { get; set; }
        public string CJGLSH { get; set; }
        public string LSHHCZT { get; set; }
        public string ZT { get; set; }
        public string WARNZT { get; set; }
        public string QUERYZT { get; set; }
        public string MEMO { get; set; }
    }
}
