//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUSINESSBASE
    {
        public string ID { get; set; }
        public string PTLB { get; set; }
        public string XTLB { get; set; }
        public string GNBH { get; set; }
        public string YWLX { get; set; }
        public string YWYY { get; set; }
        public string CYLSHISNULL { get; set; }
        public string YHPHMISNULL { get; set; }
        public string FZX { get; set; }
        public string CLLX { get; set; }
        public string SYXZ { get; set; }
        public string ZJCX { get; set; }
        public string BLMS { get; set; }
        public string SHMS { get; set; }
        public string BRZL { get; set; }
        public string DLRZL { get; set; }
        public string DWZL { get; set; }
        public string K1 { get; set; }
        public string K2 { get; set; }
        public string K3 { get; set; }
        public string MEMO { get; set; }
    }
}
