//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CKSET
    {
        public string ID { get; set; }
        public string BMNO { get; set; }
        public string BMMC { get; set; }
        public string CKMC { get; set; }
        public string IP { get; set; }
        public string KZKDZ { get; set; }
        public string WDBH { get; set; }
        public string ZCCKH { get; set; }
        public string PJCOM { get; set; }
        public string YWLXS { get; set; }
        public string CZRY { get; set; }
        public Nullable<System.DateTime> CZSJ { get; set; }
        public string ZT { get; set; }
    }
}
