//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODEYWLX
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public string LSHISNULL { get; set; }
        public string K1 { get; set; }
        public string MEMO { get; set; }
    }
}
