//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGBM
    {
        public string ID { get; set; }
        public string CID { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string KEYWORD { get; set; }
        public string NAME { get; set; }
        public string K1 { get; set; }
        public string LX1 { get; set; }
        public string V1 { get; set; }
        public string K2 { get; set; }
        public string LX2 { get; set; }
        public string V2 { get; set; }
        public string K3 { get; set; }
        public string LX3 { get; set; }
        public string V3 { get; set; }
        public string K4 { get; set; }
        public string LX4 { get; set; }
        public string V4 { get; set; }
        public string K5 { get; set; }
        public string LX5 { get; set; }
        public string V5 { get; set; }
        public Nullable<System.DateTime> OPTIME { get; set; }
        public string OPERID { get; set; }
        public string OPER { get; set; }
        public string MEMO { get; set; }
    }
}
