//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVINGLICENSE
    {
        public string DABH { get; set; }
        public string SFZMHM { get; set; }
        public string ZJCX { get; set; }
        public string YZJCX { get; set; }
        public System.DateTime QFRQ { get; set; }
        public Nullable<System.DateTime> SYRQ { get; set; }
        public System.DateTime CCLZRQ { get; set; }
        public string CCFZJG { get; set; }
        public string JZQX { get; set; }
        public System.DateTime YXQS { get; set; }
        public System.DateTime YXQZ { get; set; }
        public byte LJJF { get; set; }
        public Nullable<System.DateTime> CFRQ { get; set; }
        public Nullable<System.DateTime> XXTZRQ { get; set; }
        public byte BZCS { get; set; }
        public string ZT { get; set; }
        public string LY { get; set; }
        public string JXMC { get; set; }
        public string JLY { get; set; }
        public string XZQH { get; set; }
        public string XZQJ { get; set; }
        public System.DateTime FZRQ { get; set; }
        public string JBR { get; set; }
        public string GLBM { get; set; }
        public string FZJG { get; set; }
        public System.DateTime GXSJ { get; set; }
        public string LSH { get; set; }
        public string XGZL { get; set; }
        public string BZ { get; set; }
        public string JYW { get; set; }
        public string YDABH { get; set; }
        public string SQDM { get; set; }
        public string ZXBH { get; set; }
        public string XH { get; set; }
        public string SFZMMC { get; set; }
        public string HMCD { get; set; }
        public string XM { get; set; }
        public string XB { get; set; }
        public Nullable<System.DateTime> CSRQ { get; set; }
        public string GJ { get; set; }
        public string DJZSXZQH { get; set; }
        public string DJZSXXDZ { get; set; }
        public string LXZSXZQH { get; set; }
        public string LXZSXXDZ { get; set; }
        public string LXZSYZBM { get; set; }
        public string LXDH { get; set; }
        public string SJHM { get; set; }
        public string DZYX { get; set; }
        public string ZZZM { get; set; }
        public string ZZFZJG { get; set; }
        public Nullable<System.DateTime> ZZFZRQ { get; set; }
        public string SFBD { get; set; }
        public string DWBH { get; set; }
        public Nullable<System.DateTime> SYYXQZ { get; set; }
        public string XCZG { get; set; }
        public string XCZJCX { get; set; }
        public string RYZT { get; set; }
        public string SXBJ { get; set; }
        public Nullable<System.DateTime> XZCRQ { get; set; }
        public string SXQKSBJ { get; set; }
    }
}
