//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRV_FLOW
    {
        public string LSH { get; set; }
        public string SFZMHM { get; set; }
        public string DABH { get; set; }
        public string XM { get; set; }
        public string YWLX { get; set; }
        public string YWYY { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string YWGW { get; set; }
        public string KSKM { get; set; }
        public string XYGW { get; set; }
        public string GLBM { get; set; }
        public string FFBZ { get; set; }
        public string RKBZ { get; set; }
        public string HDBZ { get; set; }
        public string XGZL { get; set; }
        public string ZJCX { get; set; }
        public string YWZT { get; set; }
        public string YWBLBM { get; set; }
        public string FZJG { get; set; }
        public string DCBJ { get; set; }
    }
}
