//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWBADB
    {
        public string ID { get; set; }
        public string BALX { get; set; }
        public string DWLX { get; set; }
        public string DWMC { get; set; }
        public string ZZJGDM { get; set; }
        public string ADDRESS { get; set; }
        public string DWJBR { get; set; }
        public string TEL { get; set; }
        public string LXDH { get; set; }
        public string IMG1 { get; set; }
        public string URL1 { get; set; }
        public string IMG2 { get; set; }
        public string URL2 { get; set; }
        public string IMG3 { get; set; }
        public string URL3 { get; set; }
        public string IMG4 { get; set; }
        public string URL4 { get; set; }
        public string IMG5 { get; set; }
        public string URL5 { get; set; }
        public string IMG6 { get; set; }
        public string URL6 { get; set; }
        public string OPER { get; set; }
        public Nullable<System.DateTime> OPTIME { get; set; }
        public string MEMO { get; set; }
        public string MEMO1 { get; set; }
    }
}
