//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENSE
    {
        public string ID { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string PID { get; set; }
        public string BLLX { get; set; }
        public string PZLX { get; set; }
        public string PZHM { get; set; }
        public string NAME { get; set; }
        public string ZJLX { get; set; }
        public string ZJHM { get; set; }
        public string DLRNAME { get; set; }
        public string DLRZJLX { get; set; }
        public string DLRZJHM { get; set; }
        public string OPER { get; set; }
        public Nullable<System.DateTime> OPTIME { get; set; }
        public string ZZER { get; set; }
        public Nullable<System.DateTime> ZZTIME { get; set; }
        public string FFER { get; set; }
        public Nullable<System.DateTime> FFTIME { get; set; }
        public string ZT { get; set; }
        public string MEMO { get; set; }
    }
}
