//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENUDB
    {
        public string ID { get; set; }
        public string PID { get; set; }
        public string PNAME { get; set; }
        public string NAME { get; set; }
        public string ICON { get; set; }
        public string OPENMODE { get; set; }
        public string AUTO { get; set; }
        public Nullable<decimal> MINWIDTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> MINHEIGHT { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string FSCREEN { get; set; }
        public string URL { get; set; }
        public Nullable<decimal> SORT { get; set; }
        public string MEMO { get; set; }
        public string ADMIN { get; set; }
    }
}
