//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICE
    {
        public string ID { get; set; }
        public string TBLX { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string BH { get; set; }
        public string LB { get; set; }
        public string PID { get; set; }
        public string PDHM { get; set; }
        public string QHRQ { get; set; }
        public string NAME { get; set; }
        public string SFZMHM { get; set; }
        public string DABH { get; set; }
        public string ZJCX { get; set; }
        public string KEY1 { get; set; }
        public string KEY2 { get; set; }
        public string KEY3 { get; set; }
        public string KEY4 { get; set; }
        public string KEY5 { get; set; }
        public string YWLXNO { get; set; }
        public string YWLX { get; set; }
        public string HPZLNO { get; set; }
        public string HPZL { get; set; }
        public string HPHM { get; set; }
        public string CLSBHM { get; set; }
        public string FILES { get; set; }
        public string JBR { get; set; }
        public string GZRQ { get; set; }
        public Nullable<System.DateTime> GZSJ { get; set; }
        public string MEMO { get; set; }
    }
}
