//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDXX
    {
        public string XH { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string YWLXCODE { get; set; }
        public string YWLXMC { get; set; }
        public string DBRID { get; set; }
        public string DBR { get; set; }
        public string PDHM { get; set; }
        public string QHRQ { get; set; }
        public Nullable<System.DateTime> QHSJ { get; set; }
        public string BLLX { get; set; }
        public string BRNAME { get; set; }
        public string BRZJLX { get; set; }
        public string BRZJHM { get; set; }
        public string DLRNAME { get; set; }
        public string DLRZJLX { get; set; }
        public string DLRZJHM { get; set; }
        public string ISHMD { get; set; }
        public string DRVANDVEHINFO { get; set; }
        public Nullable<decimal> WAITSECOND { get; set; }
        public string DHYJ { get; set; }
        public Nullable<decimal> JHCS { get; set; }
        public Nullable<System.DateTime> JHSJ { get; set; }
        public string JHQK { get; set; }
        public string OPLOGID { get; set; }
        public string CK { get; set; }
        public string JBRID { get; set; }
        public string JBR { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTITIME { get; set; }
        public Nullable<decimal> SECOND { get; set; }
        public string BLYJ { get; set; }
        public string YWLSH { get; set; }
        public string LSHHCZT { get; set; }
        public string ZT { get; set; }
        public string QUERYZT { get; set; }
        public string TBLX { get; set; }
        public string TBYJ { get; set; }
        public string GZSID { get; set; }
        public string ZZPZ { get; set; }
        public string PZID { get; set; }
        public string TBZL { get; set; }
        public string LSHISNULL { get; set; }
    }
}
