//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBLIST
    {
        public string ID { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string LX { get; set; }
        public string DLFW { get; set; }
        public string NAME { get; set; }
        public string SFZHM { get; set; }
        public string TEL { get; set; }
        public string ZZJGDM { get; set; }
        public string DWNAME { get; set; }
        public string OPER { get; set; }
        public string OPERLX { get; set; }
        public string SPER { get; set; }
        public string JSER { get; set; }
        public string LRDAY { get; set; }
        public Nullable<System.DateTime> LRSJ { get; set; }
        public Nullable<decimal> LRSECOND { get; set; }
        public string SPDAY { get; set; }
        public Nullable<System.DateTime> SPSJ { get; set; }
        public Nullable<decimal> SPSECOND { get; set; }
        public string JSDAY { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public Nullable<decimal> JSSECOND { get; set; }
        public string ADDLX { get; set; }
        public string IMG1 { get; set; }
        public string IMG2 { get; set; }
        public string IMG3 { get; set; }
        public string IMG4 { get; set; }
        public string CAUSE { get; set; }
        public string ZT { get; set; }
        public string MEMO { get; set; }
        public string OPLOG { get; set; }
    }
}
