//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIATABLE
    {
        public string ID { get; set; }
        public string HPHM { get; set; }
        public string HPZL { get; set; }
        public string DW { get; set; }
        public string HPZLNAME { get; set; }
        public Nullable<System.DateTime> KSSJ { get; set; }
        public Nullable<System.DateTime> JSSJ { get; set; }
        public string LB { get; set; }
        public string JDCSYR { get; set; }
        public string MEMO { get; set; }
        public string SFYDD { get; set; }
        public string GXR { get; set; }
        public string LXR { get; set; }
    }
}
