//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CKSET> CKSET { get; set; }
        public virtual DbSet<CONFIGBASE> CONFIGBASE { get; set; }
        public virtual DbSet<CODE> CODE { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<BUSINESSBM> BUSINESSBM { get; set; }
        public virtual DbSet<CONFIGBM> CONFIGBM { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<BMDB> BMDB { get; set; }
        public virtual DbSet<USERDB> USERDB { get; set; }
        public virtual DbSet<CODEYWLX> CODEYWLX { get; set; }
        public virtual DbSet<MENUDB> MENUDB { get; set; }
    
        public virtual int AUTOINCPROC(ObjectParameter rET)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AUTOINCPROC", rET);
        }
    }
}
