//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRFFLOG
    {
        public string ID { get; set; }
        public string LX { get; set; }
        public string IP { get; set; }
        public string OPER { get; set; }
        public string OPDAY { get; set; }
        public Nullable<System.DateTime> OPSJ { get; set; }
        public Nullable<decimal> OPSECOND { get; set; }
        public string KEYS { get; set; }
        public string RETS { get; set; }
        public Nullable<decimal> SECOND { get; set; }
        public string ZT { get; set; }
        public string MEMO { get; set; }
    }
}
