//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERDB
    {
        public string ID { get; set; }
        public string DWNO { get; set; }
        public string DWNAME { get; set; }
        public string LOGINNAME { get; set; }
        public string NAME { get; set; }
        public string PWD { get; set; }
        public string SFZHM { get; set; }
        public Nullable<System.DateTime> MMYXQ { get; set; }
        public string TEL { get; set; }
        public string IPXZ { get; set; }
        public string IP1 { get; set; }
        public string IP2 { get; set; }
        public string IP3 { get; set; }
        public string PJXTZH { get; set; }
        public string LXDZ { get; set; }
        public string QD { get; set; }
        public string STATE { get; set; }
        public string BM { get; set; }
        public string QXLX { get; set; }
        public string QXS { get; set; }
        public string JGDWS { get; set; }
        public string FASTMENU { get; set; }
        public string MEMO { get; set; }
    }
}
