//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        public string XH { get; set; }
        public string HPZL { get; set; }
        public string HPHM { get; set; }
        public string CLPP1 { get; set; }
        public string CLXH { get; set; }
        public string CLPP2 { get; set; }
        public string GCJK { get; set; }
        public string ZZG { get; set; }
        public string ZZCMC { get; set; }
        public string CLSBDH { get; set; }
        public string FDJH { get; set; }
        public string CLLX { get; set; }
        public string CSYS { get; set; }
        public string SYXZ { get; set; }
        public string SFZMHM { get; set; }
        public string SFZMMC { get; set; }
        public string SYR { get; set; }
        public string SYQ { get; set; }
        public Nullable<System.DateTime> CCDJRQ { get; set; }
        public Nullable<System.DateTime> DJRQ { get; set; }
        public Nullable<System.DateTime> YXQZ { get; set; }
        public Nullable<System.DateTime> QZBFQZ { get; set; }
        public string FZJG { get; set; }
        public string GLBM { get; set; }
        public Nullable<System.DateTime> FPRQ { get; set; }
        public Nullable<System.DateTime> FZRQ { get; set; }
        public Nullable<System.DateTime> FDJRQ { get; set; }
        public Nullable<System.DateTime> FHGZRQ { get; set; }
        public Nullable<System.DateTime> BXZZRQ { get; set; }
        public Nullable<byte> BPCS { get; set; }
        public Nullable<byte> BZCS { get; set; }
        public Nullable<byte> BDJCS { get; set; }
        public string DJZSBH { get; set; }
        public Nullable<byte> ZDJZSHS { get; set; }
        public string DABH { get; set; }
        public string XZQH { get; set; }
        public string ZT { get; set; }
        public string DYBJ { get; set; }
        public string JBR { get; set; }
        public string CLLY { get; set; }
        public string LSH { get; set; }
        public string FDJXH { get; set; }
        public string RLZL { get; set; }
        public Nullable<int> PL { get; set; }
        public Nullable<decimal> GL { get; set; }
        public string ZXXS { get; set; }
        public Nullable<short> CWKC { get; set; }
        public Nullable<short> CWKK { get; set; }
        public Nullable<short> CWKG { get; set; }
        public Nullable<short> HXNBCD { get; set; }
        public Nullable<short> HXNBKD { get; set; }
        public Nullable<short> HXNBGD { get; set; }
        public Nullable<byte> GBTHPS { get; set; }
        public Nullable<bool> ZS { get; set; }
        public Nullable<short> ZJ { get; set; }
        public Nullable<short> QLJ { get; set; }
        public Nullable<short> HLJ { get; set; }
        public string LTGG { get; set; }
        public Nullable<byte> LTS { get; set; }
        public Nullable<int> ZZL { get; set; }
        public Nullable<int> ZBZL { get; set; }
        public Nullable<int> HDZZL { get; set; }
        public Nullable<byte> HDZK { get; set; }
        public Nullable<int> ZQYZL { get; set; }
        public Nullable<bool> QPZK { get; set; }
        public Nullable<byte> HPZK { get; set; }
        public string HBDBQK { get; set; }
        public Nullable<System.DateTime> CCRQ { get; set; }
        public string HDFS { get; set; }
        public string LLPZ1 { get; set; }
        public string PZBH1 { get; set; }
        public string LLPZ2 { get; set; }
        public string PZBH2 { get; set; }
        public string XSDW { get; set; }
        public Nullable<int> XSJG { get; set; }
        public Nullable<System.DateTime> XSRQ { get; set; }
        public string JKPZ { get; set; }
        public string JKPZHM { get; set; }
        public string HGZBH { get; set; }
        public string NSZM { get; set; }
        public string NSZMBH { get; set; }
        public Nullable<System.DateTime> GXRQ { get; set; }
        public string XGZL { get; set; }
        public string QMBH { get; set; }
        public string HMBH { get; set; }
        public string BZ { get; set; }
        public string JYW { get; set; }
        public string ZSXZQH { get; set; }
        public string ZSXXDZ { get; set; }
        public string YZBM1 { get; set; }
        public string LXDH { get; set; }
        public string ZZZ { get; set; }
        public string ZZXZQH { get; set; }
        public string ZZXXDZ { get; set; }
        public string YZBM2 { get; set; }
        public string ZDYZT { get; set; }
        public string YXH { get; set; }
        public string CYRY { get; set; }
        public string DPHGZBH { get; set; }
        public string SQDM { get; set; }
        public string CLYT { get; set; }
        public string YTSX { get; set; }
        public string DZYX { get; set; }
        public string XSZBH { get; set; }
        public string SJHM { get; set; }
        public string JYHGBZBH { get; set; }
        public string DWBH { get; set; }
        public Nullable<System.DateTime> SYQSRQ { get; set; }
        public Nullable<System.DateTime> YQJYQZBFQZ { get; set; }
        public Nullable<System.DateTime> YQJYQZ2 { get; set; }
        public Nullable<byte> FDJGS { get; set; }
        public string SFYZHGN { get; set; }
        public string ZZJGLX { get; set; }
        public string WXMBC { get; set; }
        public string NCDQSY { get; set; }
        public Nullable<System.DateTime> HPQYSJ { get; set; }
        public string DZBSXLH { get; set; }
        public string SFXNY { get; set; }
        public string XNYZL { get; set; }
        public string QDDJXH { get; set; }
        public string QDDJH { get; set; }
        public Nullable<decimal> QDDJGL { get; set; }
        public string CNZZZL { get; set; }
        public Nullable<byte> CNZZXS { get; set; }
        public Nullable<decimal> CNZZZDL { get; set; }
        public Nullable<decimal> CNZZZDY { get; set; }
        public Nullable<decimal> CNZZDTDY { get; set; }
        public string HDWJCD { get; set; }
        public Nullable<decimal> CDQDXSLCGK { get; set; }
        public Nullable<decimal> CDQDXSLCDS { get; set; }
    }
}
