//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVEH_FLOW1
    {
        public string LSH { get; set; }
        public string XH { get; set; }
        public string YWLX { get; set; }
        public string YWYY { get; set; }
        public string SYR { get; set; }
        public string HPZL { get; set; }
        public string HPHM { get; set; }
        public string CLPP1 { get; set; }
        public string CLXH { get; set; }
        public string CLLX { get; set; }
        public string XZQH { get; set; }
        public Nullable<System.DateTime> SQRQ { get; set; }
        public Nullable<System.DateTime> BJRQ { get; set; }
        public string XYGW { get; set; }
        public string YWLC { get; set; }
        public string LSZT { get; set; }
        public string GLBM { get; set; }
        public string FPBJ { get; set; }
        public string FFBJ { get; set; }
        public string RKBJ { get; set; }
        public string CLSBDH { get; set; }
        public string LY { get; set; }
        public string HDBJ { get; set; }
    }
}
