//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cgsjgpt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WARNLOG
    {
        public string ID { get; set; }
        public string DWNO { get; set; }
        public string DWMC { get; set; }
        public string WARNLX { get; set; }
        public string WARNLX1 { get; set; }
        public string XTLB { get; set; }
        public string YWLX { get; set; }
        public string NAME { get; set; }
        public string SFZMHM { get; set; }
        public string HPZLNAME { get; set; }
        public string HPHM { get; set; }
        public string CJH { get; set; }
        public string SYXZ { get; set; }
        public string DVZT { get; set; }
        public Nullable<System.DateTime> REGTIME { get; set; }
        public string GLLSH { get; set; }
        public string OPLX { get; set; }
        public string OPLX1 { get; set; }
        public string KEY1 { get; set; }
        public string KEY2 { get; set; }
        public string KEY3 { get; set; }
        public string KEY4 { get; set; }
        public string KEY5 { get; set; }
        public string KEY6 { get; set; }
        public string OPERID { get; set; }
        public string OPERNAME { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<decimal> SECOND { get; set; }
        public string OPSZT { get; set; }
        public string OPEZT { get; set; }
        public string ZT { get; set; }
        public string HCZT { get; set; }
        public string HCJG { get; set; }
        public string HCOPER { get; set; }
        public Nullable<System.DateTime> HCSJ { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MEMO1 { get; set; }
        public string MEMO2 { get; set; }
    }
}
